Repository Kakaotech-18-Ecommerce/Kakaotech-18-AI, pull requests merged in 2024-08, with the labels that each got.

#3 test upload
  test.py
Labels: feat

#5 feat: dummydata create (test.ver)
  .DS_Store
  dummy_data/buyers.json
  dummy_data/carts.json
  dummy_data/order_products.json
  dummy_data/orders.json
  dummy_data/products.json
  dummy_data/reviews.json
  dummy_data/sellers.json
Labels: feat

#7 [ES-1] create dummy data
  .DS_Store
  .idea/Kakaotech-18-AI.iml
  .idea/modules.xml
  Kakao_Dummydata.ipynb
  dummy_data/buyers.json
  dummy_data/carts.json
  dummy_data/order_products.json
  dummy_data/orders.json
  dummy_data/products.json
  dummy_data/reviews.json
  dummy_data/sellers.json
  test.py
Labels: feat

#8 SCRUM-12 <review data 개수 수정>
  Kakao_Dummydata.ipynb
  dummy_data/buyers.json
  dummy_data/carts.json
  dummy_data/order_products.json
  dummy_data/orders.json
  dummy_data/products.json
  dummy_data/reviews.json
  dummy_data/sellers.json
Labels: feat

#17 Scrum 16 data integration
  .DS_Store
  Research (EDA & Test_Model)/Kakao_Recommend_System(EDA).ipynb
  Research (EDA & Test_Model)/merged_data.csv
  dummy_data/Kakao_Dummydata.ipynb
Labels: feat

#23 [SCRUM-22] Re-Data integration & EDA
  .DS_Store
  Research (EDA & Test_Model)/.DS_Store
  Research (EDA & Test_Model)/Kakao_Recommend_System(EDA).ipynb
  Research (EDA & Test_Model)/Kakao_Recommend_System(EDA_&_CSV_Integration).ipynb
  Research (EDA & Test_Model)/merged_data.csv
  dummy_data/buyers.json
  dummy_data/carts.json
  dummy_data/order_products.json
  dummy_data/orders.json
  dummy_data/products.json
  dummy_data/reviews.json
  dummy_data/sellers.json
Labels: fix

#21 [SCRUM-20] review_star, product_quanity 추가
  dummy_data/buyers.json
  dummy_data/carts.json
  dummy_data/order_products.json
  dummy_data/orders.json
  dummy_data/products.json
  dummy_data/reviews.json
  dummy_data/sellers.json
Labels: fix

#31 SCRUM-26 Data Image & Product ID Matching
  dummy_data/products.json
Labels: feat

#33 [SCRUM-17] RecSys Model (Test.ver)
  .DS_Store
  Research (EDA & Test_Model)/.DS_Store
  Research (EDA & Test_Model)/Kakao_RecSys_Test_Model.ipynb
Labels: feat

#36 Add .DS_Store to .gitignore
  .gitignore
Labels: fix

#40 SCRUM-46 dummy data create logic - image number
  dummy_data/Kakao_Dummydata.ipynb
Labels: refactor

#43 [SCRUM-53] predict score issue
  .DS_Store
  Research (EDA & Test_Model)/Kakao_RecSys_Test_Model.ipynb
  Research (EDA & Test_Model)/Kakao_Recommend_System(EDA_&_CSV_Integration).ipynb
  Research (EDA & Test_Model)/Output_Data/Kakao_Recsys_Output.csv
  Research (EDA & Test_Model)/Output_Data/merged_data.csv
  Research (EDA & Test_Model)/Output_Data/product_predictions.json
  Research (EDA & Test_Model)/Output_Data/product_predictions_only_score.json
  dummy_data/products.json
  recommender_system/Output_Data/Kakao_Recsys_Output.csv
  recommender_system/Output_Data/product_id_with_predictions.json
  recommender_system/Output_Data/product_predictions.json
  recommender_system/model_training_and_prediction.py
Labels: fix

#55 [Scrum-18] search engine
  .DS_Store
  .gitignore
  recommender_system/category_based_recommendation.py
Labels: refactor

#56 SCRUM-54 set search engine directory
  requirements.txt
  search_engine/__init__.py
  search_engine/config.py
  search_engine/index.py
  search_engine/search_engine.py
  search_engine/utils.py
Labels: refactor

#57 [SCRUM-55] library install
  .gitignore
Labels: feat

#58 [SCRUM-56] load and preprocess data
  search_engine/data/index/MAIN_47otd9dimtt5y6rb.seg
  search_engine/data/index/MAIN_WRITELOCK
  search_engine/data/index/_MAIN_1.toc
  search_engine/index.py
Labels: feat

#60 [SCRUM-59] Implementation of basic search functionality
  search_engine/search_engine.py
Labels: feat

#61 [SCRUM-65] Added category based filtering capabilities
  search_engine/search_engine.py
Labels: feat

#62 [SCRUM-60] implementing configuration files and utilities functions
  search_engine/__init__.py
  search_engine/__pycache__/config.cpython-312.pyc
  search_engine/__pycache__/utils.cpython-312.pyc
  search_engine/config.py
  search_engine/data/index/MAIN_47otd9dimtt5y6rb.seg
  search_engine/data/index/MAIN_gcvh748xna7xdg0t.seg
  search_engine/data/index/_MAIN_1.toc
  search_engine/data/logs/search_engine.log
  search_engine/index.py
  search_engine/search_engine.py
  search_engine/utils.py
Labels: feat

#64 [SCRUM-61] Search engine test
  .DS_Store
  Research (EDA & Test_Model)/.DS_Store
  recommender_system/.DS_Store
  search_engine/.DS_Store
  search_engine/__pycache__/__init__.cpython-312.pyc
  search_engine/__pycache__/config.cpython-312.pyc
  search_engine/__pycache__/search_engine.cpython-312.pyc
  search_engine/__pycache__/utils.cpython-312.pyc
  search_engine/search_engine.py
  search_engine/utils.py
  tests/__pycache__/conftest.cpython-312-pytest-7.4.4.pyc
  tests/__pycache__/test_search_engine.cpython-312-pytest-7.4.4.pyc
  tests/conftest.py
  tests/test_search_engine.py
Labels: feat

#63 [SCRUM-64] output value research selection of models for system optimization
  Research (EDA & Test_Model)/Output_Value_Research.ipynb
  output_value_research.py
Labels: feat

#66 [SCRUM-70] Recsys model optimization file upload
  .DS_Store
  Research (EDA & Test_Model)/.DS_Store
  Research (EDA & Test_Model)/Kakao_Recommend_System(Research_Model_Optimization).ipynb
Labels: feat

#69 RecSys Model(SVM version) upload
  Research (EDA & Test_Model)/Kakao_RecSys_Test_Model(SVM_model).ipynb
Labels: feat

#71 [SCRUM-71] Model Modularization optimization operations
  Research (EDA & Test_Model)/Kakao_Recommend_System(Research_Model_Optimization).ipynb
  recommender_system/Output_Data/Kakao_Recsys_Output.csv
  recommender_system/Output_Data/model_training_results.csv
  recommender_system/Output_Data/product_id_with_predictions.json
  recommender_system/Output_Data/product_predictions.json
  recommender_system/category_based_recommendation.py
  recommender_system/main.py
  recommender_system/model_training_and_prediction.py
  recommender_system/save_results.py
Labels: refactor, feat

#72 [SCRUM-68] Search engine flask server-api & cURL test
  Research (EDA & Test_Model)/output_value_research.py
  app.py
  search_engine/__pycache__/routes.cpython-312.pyc
  search_engine/__pycache__/search_engine.cpython-312.pyc
  search_engine/__pycache__/utils.cpython-312.pyc
  search_engine/data/logs/search_engine.log
  search_engine/routes.py
Labels: ci/cd

#73 [SCRUM-67] RecSys model api communication with flask & Test
  .DS_Store
  app.py
  recommender_system/__init__.py
  recommender_system/dummy_data/products.json
  recommender_system/routes.py
  recommender_system/save_results.py
  search_engine/__pycache__/routes.cpython-312.pyc
Labels: refactor, ci/cd

#75 [SCRUM-73] Search Engine Query Improvement - Enter Keywords Only
  search_engine/__pycache__/routes.cpython-312.pyc
  search_engine/__pycache__/search_engine.cpython-312.pyc
  search_engine/data/logs/search_engine.log
  search_engine/routes.py
  search_engine/search_engine.py
Labels: fix

#76 [SCRUM-31] RecSys Model README.MD file add (explaination)
  Research (EDA & Test_Model)/Kakao_RecSys_Test_Model.ipynb
  Research (EDA & Test_Model)/Kakao_RecSys_Test_Model_json_output.ipynb
  recommender_system/README.md
  recommender_system/__init__.py
  recommender_system/category_based_recommendation.py
  recommender_system/routes.py
Labels: documentation

#78 [SCRUM-63] search_engine readme file add
  search_engine/README.md
Labels: documentation

#79 SCRUM-63 Readme 수정
  search_engine/README.md
Labels: fix, documentation

#81 [SCRUM-74] Recsys system route name fix
  recommender_system/__init__.py
  search_engine/__pycache__/routes.cpython-312.pyc
  search_engine/__pycache__/search_engine.cpython-312.pyc
  search_engine/data/logs/search_engine.log
Labels: fix
